services:
  flask:
    build:
      context: backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/code
    command: conda run --no-capture-output -n sad python /code/server.py
    ports:
      - 127.0.0.1:3001:3001
    networks:
      - sadnet
    restart: always

  ingest:
    build:
      context: backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/ingest:/code
      - ./data:/data
    command: conda run --no-capture-output -n sad python /code/ingest.py
    networks:
      - sadnet

networks:
  sadnet:
    name: sadnet
    external: true
