services:
  flask:
    container_name: sad-api
    build:
      context: backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/code
    ports:
      - 127.0.0.1:3001:3001
    networks:
      - sadnet
    restart: always
    command: conda run --no-capture-output -n sad python /code/server.py

  ingest:
    build:
      context: backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/ingest:/code
      - ./data:/data
    networks:
      - sadnet
    command: conda run --no-capture-output -n sad python /code/ingest.py
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend/app:/app
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - sadnet
    command: bash -c "rm -rf /app/node_modules; mv /deps/node_modules /app/; cd /app; HOST=0.0.0.0 npm start"

networks:
  sadnet:
    name: sadnet
    external: true
