name: test
run-name: ${{ github.actor }} is building and testing
on: 
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      - docker:dind
    steps:
      - uses: actions/checkout@v4
      - name: run tests
        run: ./build/run_tests.sh
