name: test
run-name: ${{ github.actor }} is building and testing
on: 
  pull_request:
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo hi 
#      - uses: actions/checkout@v4
#      - name: run tests
#        run: ./build/run_tests.sh
  frontend:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: build frontend
        run: ./build/build_frontend.sh
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DO_IP }}
          username: root
          key: ${{ secrets.DO_PRIVATE_KEY }}
          overwrite: true
          source: "frontend/app/build"
          target: "/root/build"
